<?php

// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-03-29 09:45

$extensionPath = t3lib_extMgm::extPath('schulungen');
$extensionClassesPath = t3lib_extMgm::extPath('schulungen') . 'Classes/';
return array(
        'tx_schulungen_command_remindercommandcontroller' => $extensionClassesPath . 'Command/ReminderCommandController.php',
	'tx_schulungen_controller_schulungcontroller' => $extensionClassesPath . 'Controller/SchulungController.php',
	'tx_schulungen_controller_emailcontroller' => $extensionClassesPath . 'Controller/EmailController.php',
	'tx_schulungen_controller_teilnehmercontroller' => $extensionClassesPath . 'Controller/TeilnehmerController.php',
	'tx_schulungen_controller_termincontroller' => $extensionClassesPath . 'Controller/TerminController.php',
	'tx_schulungen_controller_benachrichtigungcontroller' => $extensionClassesPath . 'Controller/BenachrichtigungController.php',
	'tx_schulungen_domain_model_schulung' => $extensionClassesPath . 'Domain/Model/Schulung.php',
	'tx_schulungen_domain_model_teilnehmer' => $extensionClassesPath . 'Domain/Model/Teilnehmer.php',
	'tx_schulungen_domain_model_termin' => $extensionClassesPath . 'Domain/Model/Termin.php',
	'tx_schulungen_domain_repository_schulungrepository' => $extensionClassesPath . 'Domain/Repository/SchulungRepository.php',
	'tx_schulungen_domain_repository_teilnehmerrepository' => $extensionClassesPath . 'Domain/Repository/TeilnehmerRepository.php',
	'tx_schulungen_domain_repository_terminrepository' => $extensionClassesPath . 'Domain/Repository/TerminRepository.php',
	'tx_schulungen_service_sendreminderstask' => $extensionClassesPath . 'Service/SendRemindersTask.php',
	'tx_schulungen_service_sendreminderstasklogic' => $extensionClassesPath . 'Service/SendRemindersTaskLogic.php',
	'tx_schulungen_viewhelpers_freieplaetzeviewhelper' => $extensionClassesPath . 'ViewHelpers/FreiePlaetzeViewHelper.php'
);
?>